local key = vim.keymap

key.set("n", "[a<leader>", "1k")
key.set("n", "[s<leader>", "2k")
key.set("n", "[d<leader>", "3k")
key.set("n", "[f<leader>", "4k")
key.set("n", "[g<leader>", "5k")
key.set("n", "[h<leader>", "6k")
key.set("n", "[j<leader>", "7k")
key.set("n", "[k<leader>", "8k")
key.set("n", "[l<leader>", "9k")

key.set("n", "[a;<leader>", "10k")
key.set("n", "[aa<leader>", "11k")
key.set("n", "[as<leader>", "12k")
key.set("n", "[ad<leader>", "13k")
key.set("n", "[af<leader>", "14k")
key.set("n", "[ag<leader>", "15k")
key.set("n", "[ah<leader>", "16k")
key.set("n", "[aj<leader>", "17k")
key.set("n", "[ak<leader>", "18k")
key.set("n", "[al<leader>", "19k")

key.set("n", "[s;<leader>", "20k")
key.set("n", "[sa<leader>", "21k")
key.set("n", "[ss<leader>", "22k")
key.set("n", "[sd<leader>", "23k")
key.set("n", "[sf<leader>", "24k")
key.set("n", "[sg<leader>", "25k")
key.set("n", "[sh<leader>", "26k")
key.set("n", "[sj<leader>", "27k")
key.set("n", "[sk<leader>", "28k")
key.set("n", "[sl<leader>", "29k")

key.set("n", "[d;<leader>", "30k")
key.set("n", "[da<leader>", "31k")
key.set("n", "[ds<leader>", "32k")
key.set("n", "[dd<leader>", "33k")
key.set("n", "[df<leader>", "34k")
key.set("n", "[dg<leader>", "35k")
key.set("n", "[dh<leader>", "36k")
key.set("n", "[dj<leader>", "37k")
key.set("n", "[dk<leader>", "38k")
key.set("n", "[dl<leader>", "39k")

key.set("n", "[f;<leader>", "40k")
key.set("n", "[fa<leader>", "41k")
key.set("n", "[fs<leader>", "42k")
key.set("n", "[fd<leader>", "43k")
key.set("n", "[ff<leader>", "44k")
key.set("n", "[fg<leader>", "45k")
key.set("n", "[fh<leader>", "46k")
key.set("n", "[fj<leader>", "47k")
key.set("n", "[fk<leader>", "48k")
key.set("n", "[fl<leader>", "49k")

key.set("n", "[g;<leader>", "50k")
key.set("n", "[ga<leader>", "51k")
key.set("n", "[gs<leader>", "52k")
key.set("n", "[gd<leader>", "53k")
key.set("n", "[gf<leader>", "54k")
key.set("n", "[gg<leader>", "55k")
key.set("n", "[gh<leader>", "56k")
key.set("n", "[gj<leader>", "57k")
key.set("n", "[gk<leader>", "58k")
key.set("n", "[gl<leader>", "59k")

key.set("n", "[h;<leader>", "60k")
key.set("n", "[ha<leader>", "61k")
key.set("n", "[hs<leader>", "62k")
key.set("n", "[hd<leader>", "63k")
key.set("n", "[hf<leader>", "64k")
key.set("n", "[hg<leader>", "65k")
key.set("n", "[hh<leader>", "66k")
key.set("n", "[hj<leader>", "67k")
key.set("n", "[hk<leader>", "68k")
key.set("n", "[hl<leader>", "69k")

key.set("n", "[j;<leader>", "70k")
key.set("n", "[ja<leader>", "71k")
key.set("n", "[js<leader>", "72k")
key.set("n", "[jd<leader>", "73k")
key.set("n", "[jf<leader>", "74k")
key.set("n", "[jg<leader>", "75k")
key.set("n", "[jh<leader>", "76k")
key.set("n", "[jj<leader>", "77k")
key.set("n", "[jk<leader>", "78k")
key.set("n", "[jl<leader>", "79k")

key.set("n", "[k;<leader>", "80k")
key.set("n", "[ka<leader>", "81k")
key.set("n", "[ks<leader>", "82k")
key.set("n", "[kd<leader>", "83k")
key.set("n", "[kf<leader>", "84k")
key.set("n", "[kg<leader>", "85k")
key.set("n", "[kh<leader>", "86k")
key.set("n", "[kj<leader>", "87k")
key.set("n", "[kk<leader>", "88k")
key.set("n", "[kl<leader>", "89k")

key.set("n", "[l;<leader>", "90k")
key.set("n", "[la<leader>", "91k")
key.set("n", "[ls<leader>", "92k")
key.set("n", "[ld<leader>", "93k")
key.set("n", "[lf<leader>", "94k")
key.set("n", "[lg<leader>", "95k")
key.set("n", "[lh<leader>", "96k")
key.set("n", "[lj<leader>", "97k")
key.set("n", "[lk<leader>", "98k")
key.set("n", "[ll<leader>", "99k")



key.set("n", "'a<leader>", "1j")
key.set("n", "'s<leader>", "2j")
key.set("n", "'d<leader>", "3j")
key.set("n", "'f<leader>", "4j")
key.set("n", "'g<leader>", "5j")
key.set("n", "'h<leader>", "6j")
key.set("n", "'j<leader>", "7j")
key.set("n", "'k<leader>", "8j")
key.set("n", "'l<leader>", "9j")

key.set("n", "'a;<leader>", "10j")
key.set("n", "'aa<leader>", "11j")
key.set("n", "'as<leader>", "12j")
key.set("n", "'ad<leader>", "13j")
key.set("n", "'af<leader>", "14j")
key.set("n", "'ag<leader>", "15j")
key.set("n", "'ah<leader>", "16j")
key.set("n", "'aj<leader>", "17j")
key.set("n", "'ak<leader>", "18j")
key.set("n", "'al<leader>", "19j")

key.set("n", "'s;<leader>", "20j")
key.set("n", "'sa<leader>", "21j")
key.set("n", "'ss<leader>", "22j")
key.set("n", "'sd<leader>", "23j")
key.set("n", "'sf<leader>", "24j")
key.set("n", "'sg<leader>", "25j")
key.set("n", "'sh<leader>", "26j")
key.set("n", "'sj<leader>", "27j")
key.set("n", "'sk<leader>", "28j")
key.set("n", "'sl<leader>", "29j")

key.set("n", "'d;<leader>", "30j")
key.set("n", "'da<leader>", "31j")
key.set("n", "'ds<leader>", "32j")
key.set("n", "'dd<leader>", "33j")
key.set("n", "'df<leader>", "34j")
key.set("n", "'dg<leader>", "35j")
key.set("n", "'dh<leader>", "36j")
key.set("n", "'dj<leader>", "37j")
key.set("n", "'dk<leader>", "38j")
key.set("n", "'dl<leader>", "39j")

key.set("n", "'f;<leader>", "40j")
key.set("n", "'fa<leader>", "41j")
key.set("n", "'fs<leader>", "42j")
key.set("n", "'fd<leader>", "43j")
key.set("n", "'ff<leader>", "44j")
key.set("n", "'fg<leader>", "45j")
key.set("n", "'fh<leader>", "46j")
key.set("n", "'fj<leader>", "47j")
key.set("n", "'fk<leader>", "48j")
key.set("n", "'fl<leader>", "49j")

key.set("n", "'g;<leader>", "50j")
key.set("n", "'ga<leader>", "51j")
key.set("n", "'gs<leader>", "52j")
key.set("n", "'gd<leader>", "53j")
key.set("n", "'gf<leader>", "54j")
key.set("n", "'gg<leader>", "55j")
key.set("n", "'gh<leader>", "56j")
key.set("n", "'gj<leader>", "57j")
key.set("n", "'gk<leader>", "58j")
key.set("n", "'gl<leader>", "59j")

key.set("n", "'h;<leader>", "60j")
key.set("n", "'ha<leader>", "61j")
key.set("n", "'hs<leader>", "62j")
key.set("n", "'hd<leader>", "63j")
key.set("n", "'hf<leader>", "64j")
key.set("n", "'hg<leader>", "65j")
key.set("n", "'hh<leader>", "66j")
key.set("n", "'hj<leader>", "67j")
key.set("n", "'hk<leader>", "68j")
key.set("n", "'hl<leader>", "69j")

key.set("n", "'j;<leader>", "70j")
key.set("n", "'ja<leader>", "71j")
key.set("n", "'js<leader>", "72j")
key.set("n", "'jd<leader>", "73j")
key.set("n", "'jf<leader>", "74j")
key.set("n", "'jg<leader>", "75j")
key.set("n", "'jh<leader>", "76j")
key.set("n", "'jj<leader>", "77j")
key.set("n", "'jk<leader>", "78j")
key.set("n", "'jl<leader>", "79j")

key.set("n", "'k;<leader>", "80j")
key.set("n", "'ka<leader>", "81j")
key.set("n", "'ks<leader>", "82j")
key.set("n", "'kd<leader>", "83j")
key.set("n", "'kf<leader>", "84j")
key.set("n", "'kg<leader>", "85j")
key.set("n", "'kh<leader>", "86j")
key.set("n", "'kj<leader>", "87j")
key.set("n", "'kk<leader>", "88j")
key.set("n", "'kl<leader>", "89j")

key.set("n", "'l;<leader>", "90j")
key.set("n", "'la<leader>", "91j")
key.set("n", "'ls<leader>", "92j")
key.set("n", "'ld<leader>", "93j")
key.set("n", "'lf<leader>", "94j")
key.set("n", "'lg<leader>", "95j")
key.set("n", "'lh<leader>", "96j")
key.set("n", "'lj<leader>", "97j")
key.set("n", "'lk<leader>", "98j")
key.set("n", "'ll<leader>", "99j")
